In [12]:
import numpy as np
import sys
l=range(1000)
print(sys.getsizeof(7)*len(l))
array=np.arange(1000)
print(array.size*array.itemsize)

14000
4000


In [27]:
import time
size=1000000
l1=range(size)
l2=range(size)
start=time.time()
result=[x+y for x,y in zip(l1,l2)]
print("list took : ",(time.time()-start)*1000)
a1=np.arange(size)
a2=np.arange(size)
start=time.time()
result=a1+a2
print("list took : ",(time.time()-start))

list took :  314.6507740020752
list took :  0.019986629486083984


In [32]:
a1=np.array([1,2,3,4])
a2=np.array([3,2,4,5])
r=a1-a2
print(r)

[-2  0 -1 -1]


In [34]:
a=np.array([1,4,3])
a[0]

1

In [36]:
a.ndim

1

In [42]:
a=np.array([[1,3,4],[3,4,6],[4,5,7]])
a.ndim

3

In [44]:
a=np.array([[[1,3,4],[3,4,6],[4,5,7]]])
a.ndim

3

In [47]:
print(a.itemsize) #bitsize
print(a.dtype)

4
int32


In [51]:
a=np.array([[[1,3,4],[3,4,6],[4,5,7]]],dtype=np.float64)
a.itemsize
a.dtype

dtype('float64')

In [52]:
a

array([[[1., 3., 4.],
        [3., 4., 6.],
        [4., 5., 7.]]])

In [53]:
a.size

9

In [58]:
a=np.array([[1,4,3],[4,3,2]])
a.shape

(2, 3)

In [59]:
a=np.array([[[1,3,4],[3,4,6],[4,5,7]]],dtype=complex)
a

array([[[1.+0.j, 3.+0.j, 4.+0.j],
        [3.+0.j, 4.+0.j, 6.+0.j],
        [4.+0.j, 5.+0.j, 7.+0.j]]])

In [60]:
a=np.zeros((3,2))
a

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [64]:
a=np.ones((4,4))
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [68]:
a=np.arange(2,5)
a[2]

4

In [69]:
a=np.arange(1,10,2)
a

array([1, 3, 5, 7, 9])

In [71]:
a=np.linspace(1,10,20)
a

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [82]:
a=np.array([[1,3,4,5],[3,4,5,6]])
a.shape

(2, 4)

In [86]:
a.reshape(2,4)
a

array([[1, 3, 4, 5],
       [3, 4, 5, 6]])

In [88]:
a.ravel()

array([1, 3, 4, 5, 3, 4, 5, 6])

In [89]:
a

array([[1, 3, 4, 5],
       [3, 4, 5, 6]])

In [91]:
a.min()

1

In [94]:
np.max(a)

6

In [95]:
np.sum(a)

31

In [96]:
np.sum(a,axis=0)

array([ 4,  7,  9, 11])

In [97]:
np.sum(a,axis=1)

array([13, 18])

In [98]:
np.sqrt(a)

array([[1.        , 1.73205081, 2.        , 2.23606798],
       [1.73205081, 2.        , 2.23606798, 2.44948974]])

In [99]:
np.std(a)

1.4523687548277813

In [148]:
a=np.array([[4,7],[8,3]])
b=np.array([[2,7],[9,1]])
d=a+b
d

array([[ 6, 14],
       [17,  4]])

In [141]:
c=a-b
c

array([[ 2,  0,  6],
       [-1,  2,  3]])

In [142]:
a*b

array([[ 8, 49, 27],
       [72,  3, 10]])

In [143]:
a/b

array([[2.        , 1.        , 3.        ],
       [0.88888889, 3.        , 2.5       ]])

In [149]:
a.dot(b)

array([[71, 35],
       [43, 59]])

In [151]:
a=np.array([2,6,5,4])
a[0:3]

array([2, 6, 5])

In [155]:
a=np.array([[2,5,4],[6,8,2],[5,9,1]])
a[0,2]

4

In [156]:
a[0:2,2]

array([4, 2])

In [157]:
a[-1]

array([5, 9, 1])

In [158]:
a[-1,0:2]

array([5, 9])

In [159]:
a[:,1:3]

array([[5, 4],
       [8, 2],
       [9, 1]])

In [160]:
for i in a:
    print(i)

[2 5 4]
[6 8 2]
[5 9 1]


In [162]:
b=[i for i in a]
print(b)

[array([2, 5, 4]), array([6, 8, 2]), array([5, 9, 1])]


In [167]:
for i in a.flat:
    print(i)

2
5
4
6
8
2
5
9
1


In [173]:
a=np.arange(6).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [174]:
b=np.arange(6,12).reshape(3,2)
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [175]:
np.vstack((a,b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [176]:
np.hstack((a,b))

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [177]:
a=np.arange(30).reshape(2,15)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [178]:
np.hsplit(a,3)

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]), array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]), array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [183]:
result=np.vsplit(a,2)
result[0]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]])

In [185]:
a=np.arange(12).reshape(6,2)
a

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [186]:
b=a>3
b

array([[False, False],
       [False, False],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True]])

In [187]:
a[b]

array([ 4,  5,  6,  7,  8,  9, 10, 11])

In [190]:
a[b]=-1
a

array([[ 0,  1],
       [ 2,  3],
       [-1, -1],
       [-1, -1],
       [-1, -1],
       [-1, -1]])

In [213]:
a=np.arange(12).reshape(4,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [196]:
for i in a:
    for b in i:
        print(b)

0
1
2
3
4
5
6
7
8
9
10
11


In [198]:
for cell in a.flatten():
    print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [199]:
for i in np.nditer(a,order="C"):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [200]:
for i in np.nditer(a,order='F'):
    print(i)

0
4
8
1
5
9
2
6
10
3
7
11


In [202]:
for i in np.nditer(a,order="F",flags=["external_loop"]):
    print(i)


[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [206]:
for i in np.nditer(a,op_flags=['readwrite']):
    i[...]=i*i

TypeError: Iterator operand is flagged as writeable, but is an object which cannot be written back to via WRITEBACKIFCOPY

In [215]:
b=np.arange(3,18,4).reshape(4,1)
b

array([[ 3],
       [ 7],
       [11],
       [15]])

In [216]:
for x,y in np.nditer([a,b]):
    print(x,y)

0 3
1 3
2 3
3 7
4 7
5 7
6 11
7 11
8 11
9 15
10 15
11 15
